### ISSUE TITLE
TypeError('Parameter "url" must be a string, not ' + typeof url);

### ISSUE THREAD

**Issue by StefanAntoski** [masterT/bandcamp-scraper#29]
bandcamp.getAlbumInfo('https://fasterthanmusic.bandcamp.com/album/pr4kaneokastrna-ep', function (error, albumUrls) {
                    if (error) {
                        console.log(error);
                    } else {
                        console.log(albumUrls.imageUrl);
                        }
                    }
                });

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at urlParse (url.js:97:13)
    at Url.resolve (url.js:654:29)
    at Object.urlResolve [as resolve] (url.js:650:40)
    at Object.convert (C:\Users\[User]\node_modules\bandcamp-scraper\lib\htmlParser.js:235:34)
    at C:\Users\Stefa\node_modules\scrape-it\lib\index.js:180:38
    at iterateObject (C:\Users\[User]\node_modules\iterate-object\lib\index.js:25:17)
    at handleDataObj (C:\Users\[User]\node_modules\scrape-it\lib\index.js:130:9)
    at C:\Users\[User]\node_modules\scrape-it\lib\index.js:155:32
    at iterateObject (C:\Users\[User]\node_modules\iterate-object\lib\index.js:25:17)

With every other url is working fine, but when I type this one I get this error. Idk if it's my fault or the scraper isn't working as it should.

**Comment by masterT** [comment]
Fixed in version `1.2.3` 🎉 !
